### ISSUE TITLE
Problem with single quotes

### ISSUE THREAD

**Issue by joelcuevas** [vaskovsky/notify-send#3]
Using notify-send with single quotes, i.e.:

```
 notify-send 'Hello world' 'Dummy message'
```

Breaks the title and uses only the first word:

![image](https://user-images.githubusercontent.com/275014/29849098-3cc7619e-8cea-11e7-8c45-e7c0963dfb18.png)

I think the problem is that notify-send is ignoring completely the single quotes.

I'm using notify-send to redirect the [Laravel Mix](https://laravel.com/docs/5.5/mix) notifications from [Homestead](https://laravel.com/docs/5.5/homestead) to Windows, which looks like this:

![image](https://user-images.githubusercontent.com/275014/29849289-62769cd8-8ceb-11e7-9070-3cfbc4168e39.png)

**Comment by vaskovsky** [comment]
This is not a notify-send issue. This is the difference between Unix shell and MS DOS.
Unlike Unix shell, MS DOS does not use single quotes to enquote parameters. For example, in DOS `mkdir "Hello World"` creates a folder Hello World, but `mkdir 'Hello World'` creates two folders: 'Hello and World'. If you are writing a batch file, you can use PowerShell script instead, otherwise you have to change the quotes.

**Comment by joelcuevas** [comment]
Thanks for your response.

I'm aware of the double quotes difference, I just thought that, given that your app is a good proxy for notifications from Unix VMS on Windows hosts (as suggested on [vagrant-notify](https://github.com/fgrehm/vagrant-notify)), it would be a nice feat this intercompatibility between OS. But I understand if this is not part of your scope, I can live with those Laravel notifications (probably a change like this is out of their scope too). ;)

Great work, BTW!
